platform :ios, '9.0'

target 'Brainpick' do

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.0.0'
  pod 'Firebase/Auth'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob'
  pod 'Firebase/Database'
  # pod 'Firebase/DynamicLinks'
  # pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  # pod 'Firebase/Messaging'
  # pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'

  # pod 'Fabric', '~> 1.7.6'
  # pod 'Crashlytics', '~> 3.10.1
  
end
